# Producing Variable-Page RMarkdown Documents 

### Introduction

This is a clarification on and an example of producing Rmarkdown documents that 
have a variable number of pages or HTML slides. While it is trivial to produce 
a document with a fixed number of pages (and these pages may have dynamically-
generated content), it is trickier when the final number of pages is variable.
As it turns out, the output format determines the page break character.

Suppose we have a script that will generate reports from a template for a number 
of clients, so that the reports distributed to the clients are standardized. Suppose
further that in addition to common pages (that are fixed), there are pages 
devoted to client-specific needs and each client has different needs. For example,
we may have 5 common pages that are fixed, but Client A's report includes 1
additional page (for a total 6 pages long), Client B's includes 5 additional 
pages (10 pages total) Client C's includes 2 additional pages (7 pages total), etc.
How these additional pages are generated is outside the scope of this document,
but suffice to say it could be by a for-loop.


### Code

The entire document does not have to be programmatically generated. We can have fixed 
pages and then a block (or alternating blocks) of fixed content (that may have dynamically
-generated content) with programmatically-generated pages (with variable page counts).
In order to programmatically insert a new page, we need to (1) set the output format 
of the R code block containing the page break character and (2) use the page break character
appropriate to the document we are knitting.


#### 1. Output text as raw Markdown content

When you output text from within the code sections of a Markdown document, the 
text is outputed verbatim with two leading hashes. It does so because the output
is written to the evaluated code blocks, so the output text is treated like a 
comment (i.e., is commented out). Such code is not treated as Markdown content 
and thus is ignored by knitr.

To treat the output as Markdown content instead, we must tell knitr to interpret the
code "as is" and not write it out as a comment within the fenced code output block.
We use the code chunk option `results='asis'` to set the raw output to be exactly 
the character string. 

Text to be outputted as Markdown content should be written using `cat()` instead
of `print()`; or, alternatively, `cat()` must wrap whatever you wish to write out.


#### 2. Page break character

In order for knitr to correctly recognize it, the page break character must be:

  1. on its own line by itself 
  2. surrounded by blank lines 

The character to use depends on the document output format:

- For Word and PDF documents, use `\newpage` (alternatively, `\pagebreak` also works, but any text on the page will be justified on the page)
- For HTML presentations (e.g., ioslides, slidy, beamer), use `---`
    - **NOTE:** `---` is the HTML code for a horizontal line, which the HTML 
    presentations interpret as the page break.

To complicate matters, `\newpage\` and `\pagebreak` will produce a new page/slide in an HTML 
presentation, but *only* when used outside of an R code block. `\newpage\` and `\pagebreak` will
not work if used programmatically from inside an R code block. You can use 
`\newpage\`, `\pagebreak`, and `---` inside a single HTML presentation Markdown document without
any issue, as long as they are used in the appropriate situations.

We are getting a head of ourselves, but note that if you are making plots within
loops to include on your programmatically-generated pages, you must wrap the
plot statment explicitly with print(), otherwise the plots will not be visible. 

### Example:

Use this statement to insert:

- **a new page:** `cat('\n\pagebreak\n')` 
- **a new slide:** `cat('\n---\n')`

Complete example (render to slidy if testing yourself):
``` r
---
output:
  slidy_presentation: default
  ioslides_presentation: default
  beamer_presentation: default
always_allow_html: yes
author: "Stephen Shiring"
title: "Variable Pagination Example"
date: "June 8, 2022"
---

## Fixed Slide #1

* This slide is fixed, it is specified in the RMarkdown document
* Content here may be dynamic; does not have to be.

\pagebreak

#```{r, echo=FALSE, results='asis'}  # if extracting to code to use, make sure to uncomment this line (had to comment otherwise knitr got confused)

# Slide 1: Intro
# Slide 2: Plot of sin(x)
# Slide 3: Plot of sin(pi*x)

library(ggplot2)
x = seq(0,10,0.1)

for (i in 1:3) {
  cat(paste0('\n## Variable Slide #',i,'\n'))
  
  # Some cheap logic to produce dynamic content  
  if (i == 1) {
    cat('* Content may be fixed or dynamic\n')
  } else if (i ==2) {
    cat('* Plot a sin(x)\n')
    cat('* We are getting a little bit ahead of ourselves with this example, but you must explicitly wrap the plot statement with /print() when making figures within a loop in order for them to be written\n')
    cat('* And don\'t forget to include a new line character at the end of each cat() statement!\n')
    print(qplot(x,sin(x),geom="path", xlab="time", ylab="Sine wave"))
  } else {
    cat('* Last variable page...\n')
    cat('* Plot sin(pi*x)\n')
    print(qplot(x,sin(pi*x),geom="path", xlab="time", ylab="Sine wave"))
  }
  
  cat('\n---\n')
}
```



